### ISSUE TITLE
Releasing and publishing from sbt-bintray

### ISSUE THREAD

**Issue by raisercostin** [softprops/bintray-sbt#71] opened 2015-07-29 15:39 UTC
**posted initially on http://stackoverflow.com/questions/31704818/releasing-and-publishing-from-sbt-bintray**

I'm trying to publish to bintray a relase for my library. I already released several versions [till now][1].

    java.lang.RuntimeException: error uploading to https://api.bintray.com/maven/raisercostin/maven/maven/org/raisercostin/jedi-io_2.10/0.22/jedi-io_2.10-0.22.pom: 
        {"message":"Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'org/raisercostin/jedi-io_2.10/0.22/jedi-io_2.10-0.22.pom'"}
            at bintray.BintrayMavenRepository.put(Resolver.scala:27)
            at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)

I'm using [bintray-sbt][2] via `project/plugins.sbt`

    addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")

The project with full details is hosted on [github/jedi-io][3].

I noticed a double `maven/maven` in the api url and tried to "fix" it using a custom bintray-sbt and it didn't work with either: `https://api.bintray.com/maven/raisercostin/maven/org/raisercostin/jedi-io_2.10/0.22/jedi-io_2.10-0.22.pom`

  [1]: https://bintray.com/raisercostin/maven/jedi-io/view
  [2]: https://github.com/softprops/bintray-sbt
  [3]: https://github.com/raisercostin/jedi-io

**Comment by joshcough** [comment] 2015-07-29 20:32
I had exactly the same error on a project I had previously published on July 21st.

{"message":"Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'com/localytics/kinesis-stream_2.11/0.1.1/kinesis-stream_2.11-0.1.1.pom'"}
[trace] Stack trace suppressed: run last *:publish for the full output.
[error] (*:publish) error uploading to https://api.bintray.com/maven/localytics/maven/maven/com/localytics/kinesis-stream_2.11/0.1.1/kinesis-stream_2.11-0.1.1.pom: {"message":"Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'com/localytics/kinesis-stream_2.11/0.1.1/kinesis-stream_2.11-0.1.1.pom'"}

**Comment by plamola** [comment] 2015-07-30 09:25
Seems like a Bintray issue; manual upload is also reported to fail.

As a workaround, setting `publishMavenStyle := false` and using Ivy resolving worked from me.

For details and the workaround, see this stackoverflow thread:
http://stackoverflow.com/questions/31704818/releasing-and-publishing-from-sbt-bintray

**Comment by studiodev** [comment] 2015-07-30 12:34
The problem is fixed. Thanks bintray for the quick action.

> Bintray: This issue was due to a temporary glitch in the pom verification mechanism. We have now fixed this issue.

**Closed** 2016-09-25 15:31 UTC
